using System.Text;
using System.Text.Json;
using Tomlyn;
using Tomlyn.Model;

internal sealed record SlashRouteCodegenEntry(string Path, string ArgTailKind);

/// <summary>Собирает <c>path</c> и <c>arg_tail</c> из <c>IntentMelody/intent-catalog.toml</c> (паритет с <c>IntentCatalogLoader</c>).</summary>
internal static class IntentCatalogSlashPathCollector
{
    private static readonly TomlSerializerOptions TomlOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
    };

    public static IReadOnlyList<SlashRouteCodegenEntry> Collect(string catalogPath)
    {
        var text = File.ReadAllText(catalogPath, Encoding.UTF8);
        if (TomlSerializer.Deserialize<TomlTable>(text, TomlOptions) is not TomlTable root)
            return [];

        var routes = new Dictionary<string, SlashRouteCodegenEntry>(StringComparer.OrdinalIgnoreCase);

        if (root.TryGetValue("command", out var commandNode))
            collectFromCommands(commandNode, routes);

        return routes.Values
            .OrderByDescending(static r => r.Path.Length)
            .ThenBy(static r => r.Path, StringComparer.Ordinal)
            .ToList();
    }

    private static void collectFromCommands(object? node, Dictionary<string, SlashRouteCodegenEntry> routes)
    {
        switch (node)
        {
            case TomlTableArray commands:
                foreach (var command in commands)
                    collectSlashTables(command, routes);
                break;
            case TomlTable single:
                collectSlashTables(single, routes);
                break;
        }
    }

    private static void collectSlashTables(TomlTable command, Dictionary<string, SlashRouteCodegenEntry> routes)
    {
        if (getBool(command, "enabled") == false)
            return;

        if (command.TryGetValue("slash", out var slashNode))
            collectSlashRows(slashNode, routes);

        if (!command.TryGetValue("form", out var formNode) || formNode is not TomlTable form)
            return;

        if (form.TryGetValue("slash", out var formSlash))
            collectSlashRows(formSlash, routes);
    }

    private static void collectSlashRows(object? slashNode, Dictionary<string, SlashRouteCodegenEntry> routes)
    {
        switch (slashNode)
        {
            case TomlTableArray rows:
                foreach (var row in rows)
                    addSlashRow(row, routes);
                break;
            case TomlTable single:
                addSlashRow(single, routes);
                break;
        }
    }

    private static void addSlashRow(TomlTable row, Dictionary<string, SlashRouteCodegenEntry> routes)
    {
        if (getBool(row, "enabled") == false)
            return;

        if (!row.TryGetValue("path", out var pathNode))
            return;

        var path = normalizeSlashPath(pathNode.ToString());
        if (path.Length == 0)
            return;

        var argTail = "none";
        if (row.TryGetValue("arg_tail", out var argTailNode))
            argTail = argTailNode.ToString()?.Trim().ToLowerInvariant() ?? "none";

        if (argTail is not ("none" or "optional" or "required"))
            throw new InvalidOperationException($"intent-catalog: slash '{path}' arg_tail must be none|optional|required, got '{argTail}'.");

        if (routes.ContainsKey(path))
            throw new InvalidOperationException($"intent-catalog: duplicate slash path '{path}'.");

        routes[path] = new SlashRouteCodegenEntry(path, argTail);
    }

    private static bool? getBool(TomlTable row, string key)
    {
        if (!row.TryGetValue(key, out var node))
            return null;

        return node switch
        {
            bool b => b,
            _ => bool.TryParse(node.ToString(), out var v) ? v : null,
        };
    }

    internal static string normalizeSlashPath(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return "";

        var t = raw.Trim();
        if (t.Length == 0)
            return "";

        return t[0] == '/' ? t : "/" + t;
    }
}

internal static class SlashRouteCatalogPathsEmitter
{
    public static string Emit(IReadOnlyList<SlashRouteCodegenEntry> routes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: IntentMelody/intent-catalog.toml — do not edit.");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace CascadeIDE.Services;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Codegen trie index: все slash <c>path</c> из intent-catalog (ADR 0150).</summary>");
        sb.AppendLine("internal static class SlashRouteCatalogPathsGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Канонические пути, longest-first (longest-prefix match).</summary>");
        sb.AppendLine("    public static readonly string[] PathsLongestFirst =");
        sb.AppendLine("    [");
        foreach (var route in routes)
        {
            sb.Append("        \"");
            sb.Append(Escape(route.Path));
            sb.AppendLine("\",");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    private static readonly FrozenSet<string> PathSet =");
        sb.AppendLine("        PathsLongestFirst.ToFrozenSet(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();
        sb.AppendLine("    private static readonly FrozenDictionary<string, byte> ArgTailKindByPath =");
        sb.AppendLine("        new Dictionary<string, byte>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var route in routes.OrderBy(r => r.Path, StringComparer.Ordinal))
        {
            sb.Append("            [\"");
            sb.Append(Escape(route.Path));
            sb.Append("\"] = ");
            sb.Append(argTailByte(route.ArgTailKind));
            sb.AppendLine(",");
        }
        sb.AppendLine("        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();
        sb.AppendLine("    public static bool ContainsPath(string normalizedPath) =>");
        sb.AppendLine("        PathSet.Contains(normalizedPath);");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryGetArgTailKind(string normalizedPath, out SlashRouteArgTailKind kind)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (ArgTailKindByPath.TryGetValue(normalizedPath, out var b))");
        sb.AppendLine("        {");
        sb.AppendLine("            kind = (SlashRouteArgTailKind)b;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        kind = SlashRouteArgTailKind.None;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Longest catalog path matching token prefix.</summary>");
        sb.AppendLine("    public static bool TryResolveLongestPrefix(");
        sb.AppendLine("        IReadOnlyList<string> tokens,");
        sb.AppendLine("        bool endsWithSpace,");
        sb.AppendLine("        out string canonicalPath,");
        sb.AppendLine("        out string argTail,");
        sb.AppendLine("        out bool isExactPath,");
        sb.AppendLine("        out bool endsWithSpaceAfterPath)");
        sb.AppendLine("    {");
        sb.AppendLine("        canonicalPath = \"\";");
        sb.AppendLine("        argTail = \"\";");
        sb.AppendLine("        isExactPath = false;");
        sb.AppendLine("        endsWithSpaceAfterPath = false;");
        sb.AppendLine("        if (tokens.Count == 0)");
        sb.AppendLine("            return false;");
        sb.AppendLine();
        sb.AppendLine("        for (var len = tokens.Count; len >= 1; len--)");
        sb.AppendLine("        {");
        sb.AppendLine("            var path = \"/\" + string.Join(' ', tokens.Take(len));");
        sb.AppendLine("            if (!PathSet.Contains(path))");
        sb.AppendLine("                continue;");
        sb.AppendLine();
        sb.AppendLine("            canonicalPath = path;");
        sb.AppendLine("            argTail = string.Join(' ', tokens.Skip(len));");
        sb.AppendLine("            var hasArgTail = argTail.Length > 0;");
        sb.AppendLine("            isExactPath = len == tokens.Count && !endsWithSpace && !hasArgTail;");
        sb.AppendLine("            endsWithSpaceAfterPath = endsWithSpace && !hasArgTail && len == tokens.Count;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Зеркало <see cref=\"CascadeIDE.Features.Chat.SlashArgTailKind\"/> (значения 0/1/2).</summary>");
        sb.AppendLine("internal enum SlashRouteArgTailKind : byte");
        sb.AppendLine("{");
        sb.AppendLine("    None = 0,");
        sb.AppendLine("    Optional = 1,");
        sb.AppendLine("    Required = 2,");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static int argTailByte(string kind) =>
        kind switch
        {
            "optional" => 1,
            "required" => 2,
            _ => 0,
        };

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
